import "./globals.css";
import { RouterProvider } from "../providers/router-provider";

export const metadata = {
  title: "VietSign App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* 💡 Sửa lỗi: Bao bọc children bằng RouterProvider */}
        <RouterProvider>{children}</RouterProvider>
      </body>
    </html>
  );
}
