/**
 * study Module
 * Auto-generated by migration script
 */

export * from "./components";
export * from "./components/detail";
export * from "./components/lesson";
export * from "./components/step";
